# Generated by Django 6.0.7 on 2026-07-18 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('region', models.CharField(choices=[('europe', 'Europe'), ('international', 'International')], default='europe', max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('country_slug', models.SlugField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('admission_link', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, default='A top-tier global institution offering competitive pathway routes.')),
                ('checklist_requirements', models.JSONField(blank=True, default=list, help_text='List of required files like English Certificate, MOI Letter, Passport, etc.')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('degree_type', models.CharField(choices=[('BACHELOR', 'Bachelor Degree'), ('MASTER', 'Master Degree')], default='MASTER', max_length=20)),
                ('duration_years', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tuition_per_year_usd', models.IntegerField()),
                ('language_of_instruction', models.CharField(default='English', max_length=50)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.university')),
            ],
        ),
    ]
