# Generated by Django 6.0.7 on 2026-07-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_joblisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='application_link',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='program',
            name='degree_type',
        ),
        migrations.RemoveField(
            model_name='program',
            name='duration_years',
        ),
        migrations.RemoveField(
            model_name='program',
            name='language_of_instruction',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title',
        ),
        migrations.RemoveField(
            model_name='program',
            name='tuition_per_year_usd',
        ),
        migrations.RemoveField(
            model_name='university',
            name='admission_link',
        ),
        migrations.RemoveField(
            model_name='university',
            name='checklist_requirements',
        ),
        migrations.RemoveField(
            model_name='university',
            name='city',
        ),
        migrations.RemoveField(
            model_name='university',
            name='country_slug',
        ),
        migrations.RemoveField(
            model_name='university',
            name='slug',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='university',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
